### ISSUE TITLE
python mb_cartpole.py error

### ISSUE THREAD

**Issue by mtatum7** [hanyas/trajopt#1]
I'm getting this error: 
![Screenshot from 2019-12-10 08-39-08](https://user-images.githubusercontent.com/16906155/70534217-92937300-1b28-11ea-9fe6-7c654a6b4995.png)

Do you know where trajopt.gps.core is supposed to be?

**Comment by hanyas** [comment]
You need to compile the module GPS. Please check the readme inside the GPS folder. It is a bit involved because you need to configure pybind11 and Armadillo

I will be updating the main readme soon to make installation easier.

The procedure is to prepare the libraries as described in the README in the GPS folder then run `pip install -e .` to install the whole package

**Comment by mtatum7** [comment]
I still cannot get it to run.  It's missing pybind11_DIR.  Would you be able to give explicit directions for installation and running from start to finish?

**Comment by hanyas** [comment]
Please follow the README step by step. You have to edit the path to your pybind11. 
I cannot give explicit directions. This project is presented as is.
